export const PENDING = 'PENDING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const FETCH_ROLES = 'FETCH_ROLES';
export const SHOW_UPLOAD_MODAL = 'SHOW_UPLOAD_MODAL';

// profile
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const FETCHING_PROFILE = 'FETCHING_PROFILE';

export const FETCH_STATS_STUDIES = 'FETCH_STATS_STUDIES';
export const FETCHING_STUDIES = 'FETCHING_STUDIES';
export const FETCH_STUDIES = 'FETCH_STUDIES';
export const FETCHING_TASKS = 'FETCHING_TASKS';
export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_EXPORTED_VERSIONS = 'FETCH_EXPORTED_VERSIONS';
export const FETCHING_PROJECTS = 'FETCHING_PROJECTS';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCHING_LABELS = 'FETCHING_LABELS';
export const FETCH_LABELS = 'FETCH_LABELS';
export const FETCHING_LABEL_GROUPS = 'FETCHING_LABEL_GROUPS';
export const FETCH_LABEL_GROUPS = 'FETCH_LABEL_GROUPS';
export const SET_SELECTED_LABEL_GROUPS = 'SET_SELECTED_LABEL_GROUPS';

export const FETCHING_USERS = 'FETCHING_USERS';
export const FETCH_USERS = 'FETCH_USERS';

export const FETCHING_API_KEY_LIST = 'FETCHING_API_KEY_LIST';
export const FETCH_API_KEY_LIST = 'FETCH_API_KEY_LIST';
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';

export const FETCH_PROJECT_LIST = 'FETCH_PROJECT_LIST';
export const FETCH_PROJECT_LIST_SUCCESS = 'FETCH_PROJECT_LIST_SUCCESS';
export const FETCH_PROJECT_LIST_ERROR = 'FETCH_PROJECT_LIST_ERROR';

export const FETCH_RECENT_PROJECT_LIST = 'FETCH_RECENT_PROJECT_LIST';
export const FETCH_RECENT_PROJECT_LIST_SUCCESS =
  'FETCH_RECENT_PROJECT_LIST_SUCCESS';
export const FETCH_RECENT_PROJECT_LIST_ERROR =
  'FETCH_RECENT_PROJECT_LIST_ERROR';

export const FETCH_PROJECT_DETAIL = 'FETCH_PROJECT_DETAIL';
export const FETCH_PROJECT_DETAIL_SUCCESS = 'FETCH_PROJECT_DETAIL_SUCCESS';
export const FETCH_PROJECT_DETAIL_ERROR = 'FETCH_PROJECT_DETAIL_ERROR';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_LIST_ERROR';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_ERROR = 'UPDATE_PROJECT_LIST_ERROR';

export const FETCH_RESOURCE = 'FETCH_RESOURCE';
export const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS';
export const FETCH_RESOURCE_ERROR = 'FETCH_RESOURCE_ERROR';

// API and Service monitor
export const FETCH_RESOURCE_OPS = 'FETCH_RESOURCE_OPS';
export const FETCH_RESOURCE_OPS_SUCCESS = 'FETCH_RESOURCE_OPS_SUCCESS';
export const FETCH_RESOURCE_OPS_ERROR = 'FETCH_RESOURCE_OPS_ERROR';

// Ticket
export const FETCH_TICKET = 'FETCH_TICKET';
export const FETCH_TICKET_SUCCESS = 'FETCH_TICKET_SUCCESS';
export const FETCH_TICKET_ERROR = 'FETCH_TICKET_ERROR';

// User
export const FETCH_USER_LIST = 'FETCH_USER_LIST';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR';

// Job
export const FETCH_JOB_LIST = 'FETCH_JOB_LIST';
export const FETCH_JOB_LIST_SUCCESS = 'FETCH_JOB_LIST_SUCCESS';
export const FETCH_JOB_LIST_ERROR = 'FETCH_JOB_LIST_ERROR';
